[project]
name = "pySommelier"
description = ""
version ='0.3.0'

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

